apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:    
  name: mq-qmgr  
  namespace: cp4i-acc
  labels:
    env: acc
spec:
  license:
    accept: true
    license: L-AXAF-JLZ53A
    metric: ProcessorValueUnit
    use: Development
  tracing:
    agent: {}
    collector: {}
    enabled: false
    namespace: ''
  terminationGracePeriodSeconds: 30
  securityContext:
    initVolumeAsRoot: false
    readOnlyRootFilesystem: false
  web:
    console:
      authentication:
        provider: manual
      authorization:
        provider: manual
    enabled: true
    manualConfig:
      secret:
        name: mqwebuser
  version: 9.3.4.1-r1
  telemetry:
    tracing:
      instana:
        enabled: false
        protocol: http
  template:
    pod:
      containers:
        - env:
            - name: MQSNOAUT
              value: 'yes'
          name: qmgr
          resources: {}
  queueManager:
    metrics:
      enabled: true
    resources:
      limits:
        cpu: '1'
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 1Gi
    readinessProbe:
      failureThreshold: 1
      initialDelaySeconds: 0
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 3
    route:
      enabled: true
    name: ACE12AQ01
    livenessProbe:
      failureThreshold: 1
      initialDelaySeconds: 0
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    imagePullPolicy: IfNotPresent
    debug: false
    startupProbe:
      failureThreshold: 24
      initialDelaySeconds: 0
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 5
    mqsc:
      - configMap:
          items:
            - ace12aq01
          name: ace12aq01-mqsc
    logFormat: Basic
    availability:
      type: NativeHA
      updateStrategy: RollingUpdate
    storage:
      defaultClass: gp3
      persistedData:
        class: gp3
        enabled: true
        size: 2Gi
        type: persistent-claim
      queueManager:
        class: gp3
        size: 2Gi
        type: persistent-claim
      recoveryLogs:
        enabled: false
      scratch: {}
      tmp: {}
