apiVersion: appconnect.ibm.com/v1beta1
kind: Dashboard
metadata:
  name: appconn-dashboard
  namespace: cp4i-dev
spec:
  license:
    accept: true
    license: L-MJTK-WUU8HE
    use: AppConnectEnterpriseNonProductionFREE
  pod:
    containers:
      content-server:
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 50Mi
      control-ui:
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 125Mi
  replicas: 1
  storage:
    size: 10Gi
    type: ephemeral
      #bucket: esb-poc-bar-bucket
      #host: esb-poc-bar-bucket.s3.eu-west-3.amazonaws.com
      #s3Configuration: s3-config
  useCommonServices: true
  version: '12.0.8.0-r1'
