apiVersion: appconnect.ibm.com/v1beta1
kind: DesignerAuthoring
metadata:
  name: appconn-designer-dash
  namespace: cp4i-dev
  labels:
    env: development
spec:
  couchdb:
    replicas: 1
    storage:
      class: gp3
      size: 10Gi
      type: persistent-claim
  designerFlowsOperationMode: local
  designerMappingAssist:
    enabled: true
    incrementalLearning:
      schedule: Every 15 days
  license:
    accept: true
    license: L-MJTK-WUU8HE
    use: AppConnectEnterpriseNonProductionFREE
  replicas: 2
  useCommonServices: true
  version: 12.0.8.0-r1
