kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: appconn-elb
  namespace: ibm-ace
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp2
  fsType: ext4 