apiVersion: v1
data:
  configuration: ewogICAgImF1dGhUeXBlIjoiQVdTX1NJR05BVFVSRV9WNCIsCiAgICAiY3JlZGVudGlhbHMiOnsKICAgICAgICJhY2Nlc3NLZXlJZCI6IkFLSUFZVVhQNEtOVTRISk5NT0tKIiwKICAgICAgICJzZWNyZXRBY2Nlc3NLZXkiOiJEalU2ZzM1VFdHRHhqZjJLTmNiUW1iK3B4dlFHckdwOTA2SHBVZ1FSIgogICAgfQogfQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: s3-credentials
  namespace: ibm-ace
